#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: Install Docker
  block:
    - name: Add Docker GPG apt key #Added to verify the download
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Wait for apt to unlock
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Wait for apt to unlock
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      register: check_docker_install

    - name: Wait for apt to unlock
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
      when: do_task

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
      when: do_task

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}
      when: do_task
